### ISSUE TITLE
Issue with $this->entree_model->with('user')->get_all()

### ISSUE THREAD

**Issue by faycal1** [avenirer/CodeIgniter-MY_Model#3]
Hi , 
First of all i want to thank you for the My_Model class it is very helpful ,

But i think there is an issue when i call $this->entree_model->with('user')->get_all(),
if there is tow (02) records with the same user it will display the user data only with the last entree , but it work fine if every entree has a diffrent user , sorry if it is not wll explained , is not my native language

Thank you

**Comment by avenirer** [comment]
could you show me how you defined the relationships?

**Comment by faycal1** [comment]
here is the tow models
table entrees has created_by field
class Entree_model extends MY_Model
{
    public function __construct()
    {
        $this->has_one['user'] = array('User_model','id','created_by');
        parent::__construct();
    }
}
/*********************************************************/
table a3m_account 
class User_model extends MY_Model
{
    public function __construct()
    {

```
    $this->table = 'a3m_account';
    $this->has_many['entrees'] = 'Entree_model' ;
    parent::__construct();
}
```

}

**Comment by ngangchill** [comment]
i think im facing same issue.

see my result,hope you will understand the problem.

# tables:

## blog

| id | cat_id | title |
| --- | --- | --- |
| 21 | 1 | 1st blog |
| 22 | 2 | 2nd blog |
| 23 | 2 | 3rd blog |
| 24 | 2 | 4rth blog |

## cat

| id | cat_name |
| --- | --- |
| 1 | default |
| 2 | web dev |

## Blog_model.php

```
 $this->has_one['cat'] = array('Cat_m','id','cat_id');
```

## Cat_m.php

```
$this->has_many['blog'] = 'Blog_model';
```

## Controller

```
$data = $this->blog_model->with('cat')->get_all();

 var_dump($data);
```

## query result:

array(4) {
  [0]=>
  object(stdClass)#36 (8) {
    ["id"]=>
    string(2) "21"
    ["cat_id"]=>
    string(1) "1"
    ["title"]=>
    string(8) "blog one"
    ["content"]=>
    string(32) "blog one content... demo content"
    ["user_id"]=>
    string(1) "1"
    ["created_on"]=>
    string(10) "2015-03-07"
    ["modified"]=>
    NULL
    ["cat"]=>
    array(1) {
      [0]=>
      object(stdClass)#35 (2) {
        ["id"]=>
        string(1) "1"
        ["cat_name"]=>
        string(16) "Default Category"
      }
    }
  }
  [1]=>
  object(stdClass)#25 (7) {
    ["id"]=>
    string(2) "22"
    ["cat_id"]=>
    string(1) "2"
    ["title"]=>
    string(11) "second blog"
    ["content"]=>
    string(22) "second blog content.  "
    ["user_id"]=>
    string(1) "1"
    ["created_on"]=>
    string(10) "2015-03-06"
    ["modified"]=>
    NULL
  }
  [2]=>
  object(stdClass)#24 (7) {
    ["id"]=>
    string(2) "23"
    ["cat_id"]=>
    string(1) "2"
    ["title"]=>
    string(10) "third blog"
    ["content"]=>
    string(18) "third blog content"
    ["user_id"]=>
    string(1) "2"
    ["created_on"]=>
    string(10) "2015-03-08"
    ["modified"]=>
    NULL
  }
  [3]=>
  object(stdClass)#23 (8) {
    ["id"]=>
    string(2) "24"
    ["cat_id"]=>
    string(1) "2"
    ["title"]=>
    string(9) "4rth blog"
    ["content"]=>
    string(18) "4rtj blog content "
    ["user_id"]=>
    string(1) "1"
    ["created_on"]=>
    string(10) "2015-03-07"
    ["modified"]=>
    NULL
    ["cat"]=>
    array(1) {
      [0]=>
      object(stdClass)#22 (2) {
        ["id"]=>
        string(1) "2"
        ["cat_name"]=>
        string(15) "Web Development"
      }
    }
  }
}

every query row should contain data from both table.

blog id  21 is under cat  1;
blog id  22, 23,  24 is under cat 2

### in query result: 

1st row that is 21 have data from both table,  because  cat 1 has only one entry in blog table.

but in case of same cat_id ( 2nd,,3rd, 4th row) does not have data from both table.only 4th row  that is only last one of same cat_id has data from both table.

**Comment by ngangchill** [comment]
ok.

blog id  21 is under cat  1;
blog id  22, 23,  24 is under cat 2

in query result: 

1st row that is 21 have data from both table,  [ok]
but in case of same cat_id ( 2nd,,3rd, 4th row) does not have data from both table.only 4th row  that iss only last has data from both table.

**Comment by avenirer** [comment]
I sure hope this won't break something else like pivot table relations... but I think I've repaired this problem...

**Comment by ngangchill** [comment]
thanks, it is working...

**Comment by avenirer** [comment]
fixed... I hope...

**Comment by ngangchill** [comment]
query result now ok. but error persist.

controller    

```
... ->with('comment|cat')->get_all();
```

Severity: Notice

Message: Undefined index: cat_id

Filename: core/MY_Model.php

Line Number: 578

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 578
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 704
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 465
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get_all

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

A PHP Error was encountered

Severity: Notice

Message: Undefined index:

Filename: core/MY_Model.php

Line Number: 578

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 578
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 704
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 465
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get_all

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

**Comment by avenirer** [comment]
shall we give it another try?

**Comment by faycal1** [comment]
thx you avenirer , i will give it a try

**Comment by ngangchill** [comment]
error gone  as well as result.....

on has_one relationship it is only returning first and last row from blog table.

when i use   .. with('comment')-get_all()    it works fine,(blog table has "has_many "relationship with comment table)

but when i use  ... with('cat')->get_all(); [has_one relationship ]  it return only first and last row.

thanks for your library...

im with you, just try to fix it..hope you will fix it soon...

**Comment by avenirer** [comment]
this is somewhat embarrassing. I don't know how else to tackle it...

**Comment by avenirer** [comment]
i sure hope it works

**Comment by avenirer** [comment]
@ngangchill ? @faycal1 ? anyone?

**Comment by faycal1** [comment]
Sorry avenirer , didn't have time , will check it this evening when am at home

**Comment by avenirer** [comment]
OK. Thanks. :+1:

**Comment by ngangchill** [comment]
avenenirer???

im trying it now....

**Comment by avenirer** [comment]
huraaaaaaaaaaaay...

**Comment by ngangchill** [comment]
hey!

thnx.

it is working...

**Comment by ngangchill** [comment]
....has_one/has_many/get('non_existing_id')/get('id')   [return null without error :+1: ]+/get_all()  ...  every thing are working

**Comment by avenirer** [comment]
you have the honor of closing the issue :))

**Comment by avenirer** [comment]
Thank you.

**Comment by avenirer** [comment]
Or shall we wait for @faycal1 ?

**Comment by ngangchill** [comment]
you r most welcome...    :smile:

**Comment by ngangchill** [comment]
i think it is the time to close it here...

**Comment by ngangchill** [comment]
but if you  want, we can wait for faycal1

**Comment by ngangchill** [comment]
i have a question to you!

what about the speed??

**Comment by avenirer** [comment]
I have an idea: how about doing two new relationships named has_one_through() and has_many_through() - it will be some sort of a table related to another table by one intermediary table that is not only a pivot table? This way, for example, we get the comments an author gets through its posts. Or is it too much?

**Comment by avenirer** [comment]
@ngangchill About speed. That was exactly the problem. When I've made the subqueries I thought exactly about speed (from here rose the problems). Jamie Rumbelow's MY_Model created relationships but for every single row of the results he made a subquery. My MY_Model on the other hand makes only two queries: on for the main model and one for all subqueries.

**Comment by ngangchill** [comment]
nice idea.   that  will be a great addition...

**Comment by ngangchill** [comment]
in laravel elequent:

Eager Loading

Eager loading exists to alleviate the N + 1 query problem. For example, consider a Book model that is related to Author. The relationship is defined like so:

class Book extends Model {

```
public function author()
{
    return $this->belongsTo('App\Author');
}
```

}
Now, consider the following code:

foreach (Book::all() as $book)
{
    echo $book->author->name;
}
This loop will execute 1 query to retrieve all of the books on the table, then another query for each book to retrieve the author. So, if we have 25 books, this loop would run 26 queries.

Thankfully, we can use eager loading to drastically reduce the number of queries. The relationships that should be eager loaded may be specified via the with method:

foreach (Book::with('author')->get() as $book)
{
    echo $book->author->name;
}
In the loop above, only two queries will be executed:

select \* from books

select \* from authors where id in (1, 2, 3, 4, 5, ...)
Wise use of eager loading can drastically increase the performance of your application.

Of course, you may eager load multiple relationships at one time:

$books = Book::with('author', 'publisher')->get();
You may even eager load nested relationships:

$books = Book::with('author.contacts')->get();
In the example above, the author relationship will be eager loaded, and the author's contacts relation will also be loaded.

**Comment by avenirer** [comment]
exactly. This is what i did too :))

**Comment by ngangchill** [comment]
good, only two query like laravel, sounds good, you gave the answer that i want...

**Comment by ngangchill** [comment]
do you have any intention to add fillable or guarded column?

**Comment by avenirer** [comment]
Yes, in the context of validation inside MY_Model there will be fillable and guarded properties

**Comment by faycal1** [comment]
Hi everyone , everything is workin as expected , thank you
